"""add company_name to leads

Revision ID: 71d3d43b49f8
Revises: 04fbe919cb99
Create Date: 2026-07-06 16:50:52.264726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d3d43b49f8'
down_revision: Union[str, Sequence[str], None] = '04fbe919cb99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('company_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'company_name')
    # ### end Alembic commands ###
