"""add soft delete and audit columns

Revision ID: 9e29a5036188
Revises: 909c7ebe33ca
Create Date: 2026-06-30 00:37:48.321124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e29a5036188'
down_revision: Union[str, Sequence[str], None] = '909c7ebe33ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('activities', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('companies', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('companies', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'companies', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'companies', 'users', ['created_by'], ['id'])
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('contacts', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('contacts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'contacts', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'contacts', 'users', ['created_by'], ['id'])
    op.add_column('deals', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('deals', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('deals', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'deals', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'deals', 'users', ['created_by'], ['id'])
    op.add_column('leads', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('leads', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('leads', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'leads', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'leads', 'users', ['updated_by'], ['id'])
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tasks', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'is_deleted')
    op.drop_column('tasks', 'updated_by')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'updated_at')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'deleted_at')
    op.drop_column('leads', 'is_deleted')
    op.drop_column('leads', 'updated_by')
    op.drop_column('leads', 'created_by')
    op.drop_column('leads', 'updated_at')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'deleted_at')
    op.drop_column('deals', 'is_deleted')
    op.drop_column('deals', 'updated_by')
    op.drop_column('deals', 'created_by')
    op.drop_column('deals', 'updated_at')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'deleted_at')
    op.drop_column('contacts', 'is_deleted')
    op.drop_column('contacts', 'updated_by')
    op.drop_column('contacts', 'created_by')
    op.drop_column('contacts', 'updated_at')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'deleted_at')
    op.drop_column('companies', 'is_deleted')
    op.drop_column('companies', 'updated_by')
    op.drop_column('companies', 'created_by')
    op.drop_column('companies', 'updated_at')
    op.drop_column('activities', 'deleted_at')
    op.drop_column('activities', 'is_deleted')
    # ### end Alembic commands ###